# Coin toss probability

## Tasks:
Given a set of 10 coins, with one of them unfair (both sides are tail), and all others fair.

1. We pick a coin randomly. What is the probability that this coin is unfair?
2. If we toss this coin, what is the probability that we get tail?
3. We now toss this coin and get tail. What is the probability that this coin is unfair? 4. Write a simulation to check your result obtained under 3.

In [1]:
import numpy as np

from numpy.random import default_rng

In [2]:
rng = default_rng()

Get the possible options for the fair coins (coins 0 to 8). Remember 0 is a head and 1 is a tail. We are repeating the trails 100000000 times (good statistics!).

In [5]:
fair_trials = rng.integers(0, 2, (100000000, 9))
fair_trials

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 1, 0]])

You can see that each array shows the result of the 9 coins (though of course in reality, we only flip one coin, so we wouldn't see all of these results).

Then, we simulate all the unfair tail results from coin 9 (unfair coin).

In [7]:
unfair_coin = np.ones(shape=(len(fair_trials), 1))

Combine them. This array will show the results of each of the 10 coins for 100000000 iterations.

In [8]:
all_trials = np.concatenate([fair_trials, unfair_coin], axis=1)

In [9]:
all_trials[0]

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 1.])

In [10]:
all_trials[29]

array([0., 1., 0., 0., 0., 0., 0., 1., 0., 1.])

In [11]:
all_trials[5419]

array([1., 0., 0., 1., 1., 0., 0., 1., 1., 1.])

In [14]:
sum(all_trials.flatten()) / len(all_trials.flatten())

0.549996511

This is the answer to 2, the probability of getting tail. We have summed up all the ones, which is equivalent to summing up all the tails. Then, we divided that by the total number of trials.

Set the choice of coin (i.e. from coin 0 to 9).

In [15]:
choices = rng.integers(0, 10, len(all_trials))

In [16]:
choices[8]

4

Set the chosen coin for each trial.

In [17]:
chosen_coin = np.array([itrial[c] for itrial, c in zip(all_trials, choices)])

Calculate the number of ones (i.e. tails), given that you chose coin 9 (i.e. the unfair coin).

In [19]:
faked_ones = choices[chosen_coin == 1] == 9

In [20]:
sum(faked_ones) / len(faked_ones)

0.18179068135074164

This is the answer to 3. The probability of getting an unfair coin, given that we tossed a tail.